var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var Float = require('mongoose-float').loadType(mongoose);
var eventsSchema = Schema({
    _id : Schema.Types.ObjectId,
    GLOBALEVENTID : Number,
    SQLDATE : Number,
    MonthYear : Number,
    Year : Number,
    FractionDate : Float,
    Actor1Code : String,
    Actor1Name : String,
    Actor1CountryCode : String,
    Actor1KnownGroupCode : String,
    Actor1EthnicCode : String,
    Actor1Religion1Code : String,
    Actor1Religion2Code : String,
    Actor1Type1Code : String,
    Actor1Type2Code : String,
    Actor1Type3Code : String,
    Actor2Code : String,
    Actor2Name : String,
    Actor2CountryCode : String,
    Actor2KnownGroupCode : String,
    Actor2EthnicCode : String,
    Actor2Religion1Code : String,
    Actor2Religion2Code : String,
    Actor2Type1Code : String,
    Actor2Type2Code : String,
    Actor2Type3Code : String,
    IsRootEvent : Number,
    EventCode : Number,
    EventBaseCode : Number,
    EventRootCode : Number,
    QuadClass : Number,
    GoldsteinScale : Float,
    NumMentions : Number,
    NumSources : Number,
    NumArticles : Number,
    AvgTone : Float,
    Actor1Geo_Type : Number,
    Actor1Geo_FullName : String,
    Actor1Geo_CountryCode : String,
    Actor1Geo_ADM1Code : String,
    Actor1Geo_ADM2Code : Number,
    Actor1Geo_Lat : Float,
    Actor1Geo_Long : Float,
    Actor1Geo_FeatureID : Number,
    Actor2Geo_Type : Number,
    Actor2Geo_FullName : String,
    Actor2Geo_CountryCode : String,
    Actor2Geo_ADM1Code : String,
    Actor2Geo_ADM2Code : String,
    Actor2Geo_Lat : String,
    Actor2Geo_Long : String,
    Actor2Geo_FeatureID : String,
    ActionGeo_Type : Number,
    ActionGeo_FullName : String,
    ActionGeo_CountryCode : String,
    ActionGeo_ADM1Code : String,
    ActionGeo_ADM2Code : Number,
    ActionGeo_Lat : Float,
    ActionGeo_Long : Float,
    ActionGeo_FeatureID : Number,
    DATEADDED : Number,
    SOURCEURL : String
})

module.exports = mongoose.model('Events', eventsSchema, 'cameo_events')